[pytest]
testpaths = tests
addopts = -v --alluredir=allure-results --reruns 1
python_files = test_*.py
python_classes = Test*
python_functions = test_*


markers =
    smoke: smoke test cases
    regression: regression test cases


